<?php
/** @var \Talexan\Credit\Block\Account\CustomerCoinHistory $block */
?>
<?php $_coins = $block->getCoins(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_coins && count($_coins)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Coins')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order#')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Occasion')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Amount Purchase')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Coins Received')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Coins Spend')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Created at')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_coins as $_coin) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_coin->getOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Occasion')) ?>" class="col status"><?= $block->escapeHtml($_coin->getOccasion()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Amount Purchase')) ?>" class="col total"><?= /* @noEscape */ $_coin->formatPrice($_coin->getAmountPurchase()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Coins Received')) ?>" class="col total"><?= /* @noEscape */ $block->escapeHtml($_coin->getCoinsReceived())?></td>
                        <td data-th="<?= $block->escapeHtml(__('Coins Spend')) ?>" class="col total"><?= /* @noEscape */ $block->escapeHtml($_coin->getCoinsSpend())?></td>
                        <td data-th="<?= $block->escapeHtml(__('Created at')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_coin->getCreatedAt()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyCoinsMessage()) ?></span></div>
<?php endif ?>
